import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header/SectionHeader/HeaderSection";
import Footer from "./_components/Footer/SectionFooter/SectionFooter";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const montserrat = Montserrat({
  display: "swap",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Каталог помощи иностранцам",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  const { locale } = params;
  const messages = await getMessages(locale); // Получаем сообщения для заданного локаля

  return (
    <html lang={locale}>
      <body className={`${montserrat.className} bg-white dark:bg-slate-900 text-black dark:text-white`}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main>{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
